[package]
name = "downfav"
version = "0.1.0"
authors = ["Julio Biason <julio.biason@pm.me>"]
edition = "2018"

[dependencies]
elefren = { version = "0.19", features = ["toml"] }
html2md = "0.2.9"
reqwest = "0.9.17"
log = "0.4.6"
env_logger = "0.6.1"
